version: "3.7"
services:
  server1:
    build: ./
    volumes:
      - "./proto-chain:/proto-chain"
    entrypoint: ["python", "/proto-chain/server1.py"]

  server2:
    build: ./
    depends_on:
      - "server1"
    volumes:
      - "./proto-chain:/proto-chain"
    entrypoint: ["python", "/proto-chain/server2.py", "172.23.0.2", "50082"]

  server3:
    build: ./
    depends_on:
      - "server1"
    volumes:
      - "./proto-chain:/proto-chain"
    entrypoint: ["python", "/proto-chain/server3.py", "172.23.0.2", "50082"]

#  client1:
#    build: ./
#    depends_on:
#      - "server1"
#    volumes:
#      - "./proto-chain:/proto-chain"
#    entrypoint: ["python", "/proto-chain/client1.py", "172.22.0.2", "50082"]
#
#  client2:
#    build: ./
#    depends_on:
#      - "client1"
#    volumes:
#      - "./proto-chain:/proto-chain"
#    entrypoint: ["python", "/proto-chain/client1.py", "172.22.0.2", "50082"]

networks:
  default:
